name: "Validation"

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hassfest:
    name: "Hassfest validation"
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v4

      - name: Hassfest
        uses: home-assistant/actions/hassfest@master

  hacs:
    name: "HACS validation"
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v4

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
